spring:
  application:
    name: order-service
  rabbitmq:
    host: 176.114.24.254
    port: 5672
    username: admin
    password: admin
#server:
#  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka #defaultZone，默认位置，可以修改为具体地理位置，比如：beiJing, shangHai, shenZhen 等，表示 eureka 服务器的部署位置
    registry-fetch-interval-seconds: 30 #拉取注册信息间隔时间，默认 30 秒
  instance:
    lease-renewal-interval-in-seconds: 30 #心跳间隔时间，默认 30 秒

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202